/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mapd_CiderJNI */

#ifndef _Included_com_mapd_CiderJNI
#define _Included_com_mapd_CiderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mapd_CiderJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mapd_CiderJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
