/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mapd_CiderJNI */

#ifndef _Included_com_mapd_CiderJNI
#define _Included_com_mapd_CiderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mapd_CiderJNI
 * Method:    processBlocks
 * Signature: (Ljava/lang/String;Ljava/lang/String;[J[J[J[JI)I
 */
JNIEXPORT jint JNICALL Java_com_mapd_CiderJNI_processBlocks
  (JNIEnv *, jclass, jstring, jstring, jlongArray, jlongArray, jlongArray, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
